CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(250) UNIQUE NOT NULL,
    role VARCHAR(250) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true::BOOLEAN,
    password VARCHAR(250) NOT NULL
);
